[package]
name = "ls"
version = "0.1.0"
authors = ["0xlay"]
edition = "2021"

[dependencies.windows]
version = "0.39.0"
features = [
    "Win32_Storage_FileSystem",
    "Win32_Foundation",
    "Win32_System_Time"
]